import { library } from '@fortawesome/fontawesome-svg-core';
import { faCircleCheck, faExclamationCircle, faExclamationTriangle, faPlus, faAngleRight, faAngleLeft, faAngleDoubleLeft, faAngleDoubleRight, faGreaterThan, faLessThan, faArrowRight, faArrowLeft, faEnvelope, faCaretDown, faCaretUp, faWindowClose, faPrint, faEye, faMinusSquare, faEyeSlash, faSearch, faTimes, faBars, faUser, faLock, faCheckSquare, faCoffee, faChevronDown, faChevronUp, faRedo, faHeart } from '@fortawesome/free-solid-svg-icons';

library.add(
  faCircleCheck,
  faExclamationCircle,
  faExclamationTriangle,
  faChevronDown,
  faChevronUp,
  faPlus,
  faAngleRight,
  faAngleLeft,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faGreaterThan,
  faLessThan,
  faArrowRight,
  faArrowLeft,
  faEnvelope,
  faCaretDown,
  faCaretUp,
  faWindowClose,
  faPrint,
  faMinusSquare,
  faEye,
  faEyeSlash,
  faSearch,
  faTimes,
  faBars,
  faUser,
  faLock,
  faCheckSquare,
  faCoffee,
  faRedo,
  faHeart
);