# Generated by Django 4.1.7 on 2023-05-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReportEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default=b'', max_length=100)),
                ('student_id', models.CharField(default=b'', max_length=100)),
                ('slide_no', models.CharField(default=b'', max_length=100)),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.IntegerField()),
                ('q9', models.IntegerField()),
                ('q10', models.IntegerField()),
                ('q11', models.IntegerField()),
                ('q12', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default=b'', max_length=100)),
                ('student_id', models.CharField(default=b'', max_length=100)),
                ('environment', models.CharField(default=b'', max_length=100)),
                ('lighting_condition', models.CharField(default=b'', max_length=100)),
                ('camera_spec', models.TextField(default=b'')),
                ('computer_spec', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
                ('program', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SystemDetectedEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=b'', null=True)),
                ('participant_id', models.CharField(default=b'', max_length=250)),
                ('student_id', models.CharField(default=b'', max_length=250)),
                ('emotional_engagement', models.CharField(max_length=250)),
                ('behavioral_engagement', models.CharField(max_length=250)),
                ('cognitive_engagement', models.CharField(max_length=250)),
            ],
        ),
    ]
