# Generated by Django 4.1.7 on 2023-02-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
                ('program', models.CharField(max_length=250)),
                ('camera_mod_specs', models.CharField(max_length=250)),
                ('computer_mod_specs', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('lighting_condition', models.CharField(max_length=250)),
            ],
        ),
    ]
