# Generated by Django 4.1.7 on 2023-03-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_systemdetectedengagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDetectedEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=b'')),
                ('participant_id', models.CharField(default=b'', max_length=250)),
                ('student_id', models.CharField(default=b'', max_length=250)),
                ('frame_data', models.BinaryField(blank=True, default=b'', null=True)),
                ('emotional_engagement', models.CharField(max_length=250)),
                ('behavioral_engagement', models.CharField(max_length=250)),
                ('cognitive_engagement', models.CharField(max_length=250)),
            ],
        ),
    ]
