# Generated by Django 4.1.7 on 2023-05-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemdetectedengagement_frame_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemdetectedengagement',
            name='frame_data',
        ),
    ]
