# Generated by Django 4.1.7 on 2023-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_selfreportengagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDetectedEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('time_stamp', models.CharField(max_length=250)),
                ('emotional_engagement', models.DecimalField(decimal_places=2, max_digits=3)),
                ('behavioral_engagement', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cognitive_engagement', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
