# Generated by Django 4.1.7 on 2023-03-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_systemdetectedengagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdetectedengagement',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=b'', null=True),
        ),
    ]
