# Generated by Django 4.1.7 on 2023-03-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_systemdetectedengagement_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfreportengagement',
            name='camera_spec',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='selfreportengagement',
            name='computer_spec',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='selfreportengagement',
            name='environment',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='selfreportengagement',
            name='lightning_condition',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
