# Generated by Django 4.1.7 on 2023-03-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_selfreportengagement_camera_spec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfreportengagement',
            old_name='lightning_condition',
            new_name='lighting_condition',
        ),
    ]
