# Generated by Django 4.1.7 on 2023-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_lightning_condition_selfreportengagement_lighting_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfreportengagement',
            name='camera_spec',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='selfreportengagement',
            name='computer_spec',
            field=models.TextField(default=b''),
        ),
    ]
