# Generated by Django 4.1.7 on 2023-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_selfreportengagement_camera_spec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default=b'', max_length=100)),
                ('student_id', models.CharField(default=b'', max_length=100)),
                ('environment', models.CharField(default=b'', max_length=100)),
                ('lighting_condition', models.CharField(default=b'', max_length=100)),
                ('camera_spec', models.TextField(default=b'')),
                ('computer_spec', models.TextField(default=b'')),
            ],
        ),
        migrations.RenameField(
            model_name='selfreportengagement',
            old_name='environment',
            new_name='participant_id',
        ),
        migrations.RenameField(
            model_name='selfreportengagement',
            old_name='lighting_condition',
            new_name='slide_no',
        ),
        migrations.RemoveField(
            model_name='selfreportengagement',
            name='camera_spec',
        ),
        migrations.RemoveField(
            model_name='selfreportengagement',
            name='computer_spec',
        ),
        migrations.AlterField(
            model_name='selfreportengagement',
            name='student_id',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
